[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/series"
  to = "/shows"
  status = 301

[[redirects]]
  from = "/tv/:id"
  to = "/show/:id"
  status = 301
