export const singleTv = {
  backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
  created_by: [
    {
      id: 82725,
      credit_id: "590e3f13c3a368650a013106",
      name: "Álex Pina",
      gender: 2,
      profile_path: "/hMKcFPRKo0I4WLBvkvppyBFDGr8.jpg",
    },
  ],
  episode_run_time: [70, 47],
  first_air_date: "2017-05-02",
  genres: [
    {
      id: 80,
      name: "Crime",
    },
    {
      id: 18,
      name: "Drama",
    },
  ],
  homepage: "https://www.netflix.com/title/80192098",
  id: 71446,
  in_production: false,
  languages: ["es"],
  last_air_date: "2021-12-03",
  last_episode_to_air: {
    air_date: "2021-12-03",
    episode_number: 10,
    id: 3101456,
    name: "A Family Tradition",
    overview:
      "With multiple lives on the line and Spain's economy at stake, the Professor and Tamayo engage in one final showdown.",
    production_code: "",
    season_number: 3,
    still_path: "/ilpHAUoDo7xM9YBBD2oFi1q6krQ.jpg",
    vote_average: 5.5,
    vote_count: 4,
  },
  name: "Money Heist",
  next_episode_to_air: null,
  networks: [
    {
      name: "Netflix",
      id: 213,
      logo_path: "/wwemzKWzjKYJFfCeiB57q3r4Bcm.png",
      origin_country: "",
    },
    {
      name: "Antena 3",
      id: 400,
      logo_path: "/l7MngINTyv0O6mNlwNsUlhQ9iwZ.png",
      origin_country: "ES",
    },
  ],
  number_of_episodes: 41,
  number_of_seasons: 3,
  origin_country: ["ES"],
  original_language: "es",
  original_name: "La Casa de Papel",
  overview:
    "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
  popularity: 1948.447,
  poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
  production_companies: [
    {
      id: 100783,
      logo_path: "/zCbBliLd81vorYMSBT3vkv5sHYL.png",
      name: "Vancouver Media",
      origin_country: "ES",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "ES",
      name: "Spain",
    },
  ],
  seasons: [
    {
      air_date: "2017-12-20",
      episode_count: 22,
      id: 150472,
      name: "Specials",
      overview: "",
      poster_path: "/8LVa0SOIiXY2frFmCp7uVJXWwvm.jpg",
      season_number: 0,
    },
    {
      air_date: "2017-05-02",
      episode_count: 15,
      id: 87809,
      name: "Season 1",
      overview:
        "Under the guidance of The Professor, a group of eight very peculiar robbers have attacked the National Coinage and Stamp Factory of Spain and took hostages to carry out the most perfect robbery in the history, aiming to take home 2.4 billion Euros in cash.",
      poster_path: "/jAGeeCuAh4Id4p78BOYsSFXLrC8.jpg",
      season_number: 1,
    },
    {
      air_date: "2019-07-20",
      episode_count: 16,
      id: 122186,
      name: "Season 2",
      overview:
        "The Professor and his team reunite to free Rio, this time targeting the Bank of Spain with a daring and dangerous new plan. The Resistance continues.",
      poster_path: "/bp2MEZT8dsl33ULA8RA1IK6ZbZ.jpg",
      season_number: 2,
    },
    {
      air_date: "2021-09-03",
      episode_count: 10,
      id: 201800,
      name: "Season 3",
      overview:
        "Three years after the heist on the Royal Mint of Spain, the robbers are enjoying their lives paired-up in diverse locations.",
      poster_path: "/kJxqdEfInoai6Ca2tUEWbelveUP.jpg",
      season_number: 3,
    },
  ],
  spoken_languages: [
    {
      english_name: "Spanish",
      iso_639_1: "es",
      name: "Español",
    },
  ],
  status: "Ended",
  tagline: "The perfect robbery.",
  type: "Scripted",
  vote_average: 8.3,
  vote_count: 15497,
  external_ids: {
    imdb_id: "tt6468322",
    freebase_mid: null,
    freebase_id: null,
    tvdb_id: 327417,
    tvrage_id: null,
    facebook_id: "lacasadepapelnetflix",
    instagram_id: "lacasadepapel",
    twitter_id: "lacasadepapel",
  },
  keywords: {
    results: [
      {
        name: "robbery",
        id: 642,
      },
      {
        name: "stockholm syndrome",
        id: 278,
      },
      {
        name: "spain",
        id: 514,
      },
      {
        name: "perfect crime",
        id: 584,
      },
      {
        name: "professor",
        id: 1992,
      },
      {
        name: "heist",
        id: 10051,
      },
      {
        name: "flashback",
        id: 9856,
      },
      {
        name: "sexual tension",
        id: 11518,
      },
      {
        name: "bank robbery",
        id: 15363,
      },
      {
        name: "hostage situation",
        id: 18233,
      },
      {
        name: "tunnel",
        id: 189102,
      },
    ],
  },
  credits: {
    cast: [
      {
        adult: false,
        gender: 2,
        id: 1340020,
        known_for_department: "Acting",
        name: "Álvaro Morte",
        original_name: "Álvaro Morte",
        popularity: 17.591,
        profile_path: "/2TGPhdpRC5wjdFEJqnLYiN5kbwg.jpg",
        character: "Sergio 'El Profesor' Marquina / Salvador 'Salva' Martin",
        credit_id: "5d3376536a300b1834ac44e5",
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 1042728,
        known_for_department: "Acting",
        name: "Úrsula Corberó",
        original_name: "Úrsula Corberó",
        popularity: 40.447,
        profile_path: "/noNEe22FM78cYuNGH9jwdQ6rdA8.jpg",
        character: "Silene 'Tokio' Oliveira",
        credit_id: "5a422574c3a36858c5036f41",
        order: 1,
      },
      {
        adult: false,
        gender: 1,
        id: 947514,
        known_for_department: "Acting",
        name: "Itziar Ituño",
        original_name: "Itziar Ituño",
        popularity: 21.925,
        profile_path: "/vnrfL03NwRJ1X82esSNUoYzASGr.jpg",
        character: "Raquel Murillo",
        credit_id: "5a4225d29251411fab04d6ea",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 1109836,
        known_for_department: "Acting",
        name: "Pedro Alonso",
        original_name: "Pedro Alonso",
        popularity: 10.333,
        profile_path: "/38HeVKeOBztVYrLJOWzAtEZiB02.jpg",
        character: "Andrés 'Berlin' de Fonollosa",
        credit_id: "5d34b7bd17792c0012bcac8d",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 1972706,
        known_for_department: "Acting",
        name: "Jaime Lorente",
        original_name: "Jaime Lorente",
        popularity: 11.277,
        profile_path: "/nLaxzU92z14FIbe25sE8jDMIThZ.jpg",
        character: "Dani 'Denver' Ramos",
        credit_id: "5a773f46c3a3682273001229",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 1428896,
        known_for_department: "Acting",
        name: "Miguel Herrán",
        original_name: "Miguel Herrán",
        popularity: 15.738,
        profile_path: "/jJ8UKek4GvQrQUP9q97Kq2MWVqi.jpg",
        character: "Aníbal 'Río' Cortés",
        credit_id: "5a4227c89251411f4f04a5b3",
        order: 5,
      },
      {
        adult: false,
        gender: 1,
        id: 1972707,
        known_for_department: "Acting",
        name: "Esther Acebo",
        original_name: "Esther Acebo",
        popularity: 17.825,
        profile_path: "/2v2eOKCjnQfY3jCsowtH8wLxFMC.jpg",
        character: "Mónica Gaztambide",
        credit_id: "5a773f680e0a26598500132a",
        order: 6,
      },
      {
        adult: false,
        gender: 2,
        id: 18478,
        known_for_department: "Acting",
        name: "Rodrigo de la Serna",
        original_name: "Rodrigo de la Serna",
        popularity: 7.807,
        profile_path: "/vMuKUJSnEGOmjjLYzVDKGukiaCr.jpg",
        character: "Martín 'Palermo' Berrote",
        credit_id: "5d2e07af839d93000eefbc63",
        order: 7,
      },
      {
        adult: false,
        gender: 2,
        id: 944099,
        known_for_department: "Acting",
        name: "Enrique Arce",
        original_name: "Enrique Arce",
        popularity: 4.903,
        profile_path: "/1lACQepfukuZ0l6FnUpMO03WxcJ.jpg",
        character: "Arturo Román",
        credit_id: "5a773eeac3a368227b001336",
        order: 8,
      },
      {
        adult: false,
        gender: 2,
        id: 1898026,
        known_for_department: "Acting",
        name: "Darko Peric",
        original_name: "Darko Peric",
        popularity: 8.03,
        profile_path: "/9IsIRW3PE105bfwen4IzGPXfmQc.jpg",
        character: "Mirko 'Helsinki' Dragic",
        credit_id: "5a773f9a92514177690011a6",
        order: 9,
      },
      {
        adult: false,
        gender: 2,
        id: 1131415,
        known_for_department: "Acting",
        name: "Hovik Keuchkerian",
        original_name: "Hovik Keuchkerian",
        popularity: 4.9,
        profile_path: "/o5cGKWHlZl4RFROYlT2hD95j0lN.jpg",
        character: "Santiago 'Bogotá' López",
        credit_id: "5d2e078f6a300b000fa4d50c",
        order: 10,
      },
      {
        adult: false,
        gender: 2,
        id: 1076809,
        known_for_department: "Acting",
        name: "Luka Peroš",
        original_name: "Luka Peroš",
        popularity: 6.556,
        profile_path: "/lfh7959EpR9gAvrjObNGXaUg2qF.jpg",
        character: "Jakov 'Marsella'",
        credit_id: "610d419d323eba005dd9c933",
        order: 11,
      },
      {
        adult: false,
        gender: 1,
        id: 1423493,
        known_for_department: "Acting",
        name: "Belén Cuesta",
        original_name: "Belén Cuesta",
        popularity: 12.993,
        profile_path: "/xxaNCeIuLh7nZvuCrwANO3zwI5g.jpg",
        character: "Julia Martínez",
        credit_id: "610d41ae5a4690005ff40b54",
        order: 12,
      },
      {
        adult: false,
        gender: 2,
        id: 51902,
        known_for_department: "Acting",
        name: "Fernando Cayo",
        original_name: "Fernando Cayo",
        popularity: 5.768,
        profile_path: "/sglfXHNFlzOBBLuRrbDkxghSW4H.jpg",
        character: "Luis Tamayo",
        credit_id: "610d41fa323eba005dd9c9d8",
        order: 13,
      },
      {
        adult: false,
        gender: 1,
        id: 16442,
        known_for_department: "Acting",
        name: "Najwa Nimri",
        original_name: "Najwa Nimri",
        popularity: 18.422,
        profile_path: "/hvLbKkDIT4FqSS8djmW5voNd0O4.jpg",
        character: "Alicia Sierra",
        credit_id: "5d2e09e8caab6d1e81a3b6f2",
        order: 14,
      },
    ],
    crew: [],
  },
  videos: {
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Money Heist | Series Trailer | Netflix",
        key: "_InqQJRqGW4",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2021-12-01 14:00:00 UTC",
        id: "61aa09cec5c1ef00672001a5",
      },
    ],
  },
  similar: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/2g7bmcbYeuwGUlim9APyHnzPe1Q.jpg",
        genre_ids: [18, 10759],
        id: 5829,
        name: "Flashpoint",
        origin_country: ["CA"],
        original_language: "en",
        original_name: "Flashpoint",
        overview:
          "The Strategic Response Unit (SRU) is an elite team of cops who specialize in high-risk critical incidents. Trained in tactics and psychology, they deal with extreme situations, where split-second decisions could save a life...or cost one.",
        popularity: 27.973,
        poster_path: "/3Bp3vJrPxnrN8iRDaclsVUPwgWa.jpg",
        first_air_date: "2008-07-11",
        vote_average: 7.4,
        vote_count: 84,
      },
      {
        adult: false,
        backdrop_path: "/iP9Xjlc8KRmXE0kVMTaJRaN0umh.jpg",
        genre_ids: [18, 10759, 10765],
        id: 1437,
        name: "Firefly",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Firefly",
        overview:
          'In the year 2517, after the arrival of humans in a new star system, follow the adventures of the renegade crew of Serenity, a "Firefly-class" spaceship. The ensemble cast portrays the nine characters who live on Serenity.',
        popularity: 29.471,
        poster_path: "/vZcKsy4sGAvWMVqLluwYuoi11Kj.jpg",
        first_air_date: "2002-09-20",
        vote_average: 8.289,
        vote_count: 1452,
      },
      {
        adult: false,
        backdrop_path: "/jxuNxwQBpBjYEttwKgr0oB6TGv1.jpg",
        genre_ids: [35, 18],
        id: 7897,
        name: "Cuéntame Cómo Pasó",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Cuéntame Cómo Pasó",
        overview:
          "Recounts the experiences of a middle-class family, the Alcántaras, during the last years of the rule of Francisco Franco and the beginning of the Spanish Transition to democracy.",
        popularity: 16.633,
        poster_path: "/fIqicSw67DonOgC7F9Rik4RxL4R.jpg",
        first_air_date: "2001-09-13",
        vote_average: 6.3,
        vote_count: 29,
      },
      {
        adult: false,
        backdrop_path: "/1ot3DeWBHaI3cbfQtqZqOI1VoPI.jpg",
        genre_ids: [18, 9648],
        id: 19614,
        name: "It",
        origin_country: ["US"],
        original_language: "en",
        original_name: "It",
        overview:
          'In 1960, seven outcast kids known as "The Losers\' Club" fight an evil demon who poses as a child-killing clown. Thirty years later, they reunite to stop the demon once and for all when it returns to their hometown.',
        popularity: 67.441,
        poster_path: "/4ybQ6gopB3H3cu0seVZLznDnIKo.jpg",
        first_air_date: "1990-11-18",
        vote_average: 6.873,
        vote_count: 2370,
      },
      {
        adult: false,
        backdrop_path: "/aiEblNA6Ww4jzKZiqQbfpv8XpzQ.jpg",
        genre_ids: [18, 35, 10759, 80],
        id: 34376,
        name: "Los hombres de Paco",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Los hombres de Paco",
        overview: "",
        popularity: 27.673,
        poster_path: "/o18qCrSlgQXoRIDwCRiIz9IPyqY.jpg",
        first_air_date: "2005-10-09",
        vote_average: 8.119,
        vote_count: 143,
      },
      {
        adult: false,
        backdrop_path: "/nXmxvy4VyiaYVVINJYARSD3CTLi.jpg",
        genre_ids: [35, 10751, 18],
        id: 7283,
        name: "Los Serrano",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Los Serrano",
        overview:
          'Los Serrano is a Spanish television drama comedy which premiered on 22 April 2003 and aired on Telecinco. It tells the story of the Serrano family, who lives in Round Santa Justa No 133, located in the fictional neighborhood of Santa Justa, in the Ribera del Manzanares, in Madrid. The success of the series in Spain and in several other countries in Europe and elsewhere helped launch the career of several young actors and actresses, especially actor and musician Fran Perea, who acts in the series and sings its theme song, "1 más 1 son 7".',
        popularity: 15.553,
        poster_path: "/w9hPecVLyCkbnJLLdjFu67URBZP.jpg",
        first_air_date: "2003-04-22",
        vote_average: 5.8,
        vote_count: 21,
      },
      {
        adult: false,
        backdrop_path: "/fOLKnuODub9EGwLGzlhjr8g1khp.jpg",
        genre_ids: [18],
        id: 61260,
        name: "Velvet",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Velvet",
        overview:
          "In 1950s Spain, the heir to a fashion house romances a beautiful seamstress who works for the company, despite the objections of his family.",
        popularity: 32.16,
        poster_path: "/2MvMjjdY1zNIKEjiTsbngzdYYfy.jpg",
        first_air_date: "2014-01-17",
        vote_average: 6.029,
        vote_count: 34,
      },
      {
        adult: false,
        backdrop_path: "/1qdqPghGXPIX49WWjhehgPSDXKi.jpg",
        genre_ids: [18, 9648],
        id: 47990,
        name: "Grand Hotel",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Gran Hotel",
        overview:
          "Grand Hotel is a Spanish drama television series directed by Carlos Sedes and starring Yon Gonzalez and Amaia Salamanca. It first aired on Antena 3 in Spain on 11 October 2011 and on Sky Arts 1 in the UK on 18 November 2012.\n\nThe series, filmed at the Palacio de la Magdalena in Santander, is set in an early 20th century aristocratic hotel during the reign of King Alfonso XIII and is centered on the mysteries that involve the owner family and the hotel servants. Grand Hotel has received critical acclaim from television critics and won numerous accolades.",
        popularity: 30.517,
        poster_path: "/hAEWiDY5trfg0JRVaGGyea6Cepk.jpg",
        first_air_date: "2011-05-10",
        vote_average: 7.385,
        vote_count: 39,
      },
      {
        adult: false,
        backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
        genre_ids: [80, 18],
        id: 71446,
        name: "Money Heist",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "La Casa de Papel",
        overview:
          "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
        popularity: 1948.447,
        poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
        first_air_date: "2017-05-02",
        vote_average: 8.295,
        vote_count: 15496,
      },
      {
        adult: false,
        backdrop_path: "/nanLj19kHrnv3yBzaOKcMTVDK03.jpg",
        genre_ids: [35, 18],
        id: 67136,
        name: "This Is Us",
        origin_country: ["US"],
        original_language: "en",
        original_name: "This Is Us",
        overview:
          "Follows the lives and families of three adults living and growing up in the United States of America in present and past times. As their paths cross and their life stories intertwine in curious ways, we find that several of them share the same birthday - and so much more than anyone would expect.",
        popularity: 65.59,
        poster_path: "/bPaVOvW2LK6oYrRv9Ybb196ywub.jpg",
        first_air_date: "2016-09-20",
        vote_average: 8.194,
        vote_count: 1010,
      },
      {
        adult: false,
        backdrop_path: "/fRJD9SVaXxDz3dipgn6UzATuKjj.jpg",
        genre_ids: [80, 18],
        id: 69309,
        name: "Ransom",
        origin_country: ["CA"],
        original_language: "en",
        original_name: "Ransom",
        overview:
          "Eric Beaumont's crisis negotiator team is brought in to save lives and resolve the most difficult kidnap and ransom cases when no one else can.",
        popularity: 28.724,
        poster_path: "/msn327MnlMG2iMess6CSTcn3HT2.jpg",
        first_air_date: "2017-01-01",
        vote_average: 6.18,
        vote_count: 61,
      },
      {
        adult: false,
        backdrop_path: "/fTiD5eo4i8Mt90Ww9Ab8B2n94Kl.jpg",
        genre_ids: [18, 10759],
        id: 62099,
        name: "The Ministry of Time",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "El Ministerio del Tiempo",
        overview:
          "A soldier from the 15th century, a university student from the 19th century and a nurse from the present join the secret 'Department of Time', a secret department within the Spanish government with the ability to travel through time. Their mission is prevent changes in history.",
        popularity: 34.847,
        poster_path: "/sNv6aE47PTTTpHknT3gzmF2rBgh.jpg",
        first_air_date: "2015-02-24",
        vote_average: 7.389,
        vote_count: 99,
      },
      {
        adult: false,
        backdrop_path: "/eqOAW52GkgbMDGIzpqlz8zwTIiO.jpg",
        genre_ids: [18],
        id: 86428,
        name: "The Spanish Princess",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Spanish Princess",
        overview:
          "The beautiful Spanish princess, Catherine of Aragon, navigates the royal lineage of England with an eye on the throne.",
        popularity: 34.591,
        poster_path: "/4Ec0jIkctpiyKuywPSRj4Pd2jEl.jpg",
        first_air_date: "2019-05-05",
        vote_average: 7.646,
        vote_count: 355,
      },
      {
        adult: false,
        backdrop_path: "/eindfDG2l77gBGqaspGvzn8DOTF.jpg",
        genre_ids: [10759, 80, 18],
        id: 117023,
        name: "Sky Rojo",
        origin_country: ["ES"],
        original_language: "es",
        original_name: "Sky Rojo",
        overview:
          "On the run from their pimp and his henchmen, three women embark on a wild and crazy journey in search of freedom.",
        popularity: 65.006,
        poster_path: "/uTFX9V2dct1nKjG6zhNiThPm8Tp.jpg",
        first_air_date: "2021-03-19",
        vote_average: 7.8,
        vote_count: 348,
      },
      {
        adult: false,
        backdrop_path: "/nB8Z2lDOOSpZgTRLUVYSJ74RPof.jpg",
        genre_ids: [10765, 10759, 18],
        id: 75758,
        name: "Lost in Space",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Lost in Space",
        overview:
          "After crash-landing on an alien planet, the Robinson family fights against all odds to survive and escape. But they're surrounded by hidden dangers.",
        popularity: 241.939,
        poster_path: "/y8NJnTXzb4rio9uvVYFVrXEMofU.jpg",
        first_air_date: "2018-04-13",
        vote_average: 7.6,
        vote_count: 983,
      },
      {
        adult: false,
        backdrop_path: "/1t4LUrNNWrSrTPt2BpTWyTn8qcn.jpg",
        genre_ids: [99],
        id: 111052,
        name: "The Secret World of Nature: Spain",
        origin_country: ["ES", "US"],
        original_language: "en",
        original_name: "The Secret World of Nature: Spain",
        overview:
          "More than four years of filming have been necessary to capture the impressive images of the most varied animal species that inhabit the Iberian Peninsula: amphibians, reptiles, mammals, birds, insects and fish are represented in this wonderful journey through the different ecosystems that we can find in Iberian lands.",
        popularity: 13.397,
        poster_path: "/8WeJUtRvLPEAFpJsrYowkMipTGe.jpg",
        first_air_date: "2020-07-01",
        vote_average: 9.6,
        vote_count: 26,
      },
      {
        adult: false,
        backdrop_path: "/6INgu5jdxz2o1IzEZuh9Z7f1yML.jpg",
        genre_ids: [9648, 10759],
        id: 50558,
        name: "Crisis",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Crisis",
        overview:
          "When Washington's most powerful players are pulled into an international conspiracy, an unlikely puppeteer will bring everyone from CEOs to The President of the United States to their knees by threatening the things they hold most dear. ",
        popularity: 14.407,
        poster_path: "/BvcrUL7G9mVZo7YrfC5uWu4fpa.jpg",
        first_air_date: "2014-03-16",
        vote_average: 6.282,
        vote_count: 94,
      },
      {
        adult: false,
        backdrop_path: "/muDbxqoMoyeePjm5gTXt3LXNE1W.jpg",
        genre_ids: [16, 80, 18, 9648],
        id: 69225,
        name: "ACCA: 13-Territory Inspection Dept.",
        origin_country: ["JP"],
        original_language: "ja",
        original_name: "ACCA13区監察課",
        overview:
          "\"ACCA\" is a giant unified syndicate residing in a kingdom split into 13 autonomous regions. ACCA was formed back when there was threat of a coup d'etat, and has continued to protect the peace for almost one hundred years. Jean Otus, vice-chairman of the inspections department at ACCA headquarters, wanders through the 13 districts, checking to see if there is any foul play afoot. His quiet everyday life slowly gets swallowed up into the world's conspiracies!",
        popularity: 13.118,
        poster_path: "/bEqDCv7IZBfM5mLMeAObvfKxJ9l.jpg",
        first_air_date: "2017-01-10",
        vote_average: 7.1,
        vote_count: 35,
      },
      {
        adult: false,
        backdrop_path: "/fhkaFQzQ5Mm1co0RIsaDTs7ZxJ9.jpg",
        genre_ids: [10759, 80, 18, 9648],
        id: 56336,
        name: "The Tunnel",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "The Tunnel",
        overview:
          'The plot follows detectives Karl Roebuck and Elise Wasserman working together to find a serial killer who left the upper-half body of a French politician and the lower-half of a British prostitute in the Channel Tunnel, at the midpoint between France and the UK. They later learn that the killer—who comes to be nicknamed the "Truth Terrorist"—is on a moral crusade to highlight many social problems, terrorising both countries in the process',
        popularity: 8.031,
        poster_path: "/qpuGcfrFjvjsEHtuVjyTVQCWNzV.jpg",
        first_air_date: "2013-10-16",
        vote_average: 7.654,
        vote_count: 52,
      },
      {
        adult: false,
        backdrop_path: "/8xPe5b6GsBF9PgkU1kjfdnKfGbq.jpg",
        genre_ids: [80, 99],
        id: 79126,
        name: "Evil Genius",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Evil Genius",
        overview:
          "This baffling true crime story starts with the grisly death of a pizza man who robs a bank with a bomb around his neck - and gets weirder from there.",
        popularity: 13.566,
        poster_path: "/nyG5snyr6nqbIBwn6vTCYFQkxsi.jpg",
        first_air_date: "2018-05-11",
        vote_average: 7.504,
        vote_count: 118,
      },
    ],
    total_pages: 500,
    total_results: 10000,
  },
};
