module.exports = {
  pathPrefix: "/",
  title: "Movie Handbook",
  titleAlt: "Movies",
  description: "Search your favorite movies.",
  headline: "Movie search",
  url: "https://movie-handbook.netlify.app/",
  siteLanguage: "en",
  ogLanguage: "en_US",
  author: "Ha Truong",
  banner: "src/images/cover.jpg",
  favicon: "src/images/favicon.svg",
  shortName: "MH",
  author: "Ha Truong",
  themeColor: "#3D63AE",
  backgroundColor: "#EBEDF2",
  twitter: "@expatolife",
  facebook: "expatolife",
};
